### PR TITLE
Don't treat falsy literals as variables (a.k.a. None)

### LINKED ISSUE #9: Falsy literals are treated as variables
The following test fails:
```py
def test_falsy_literals(self):
    self.graph.add((artis, EX["prop"], Literal("")))
    self.graph.add((artis, EX["prop"], Literal(False)))

    self.assertEquals(
        list(self.graph.triples((artis, EX["prop"], Literal("")))),
        [(artis, EX["prop"], Literal(""))]
    )

    self.graph.remove((artis, EX["prop"], Literal("")))
    self.assertEquals(
        list(self.graph),
        [(artis, EX["prop"], Literal(False))]
    )
```
Because...
- it crashes because it tries to use an `URIStatement` for the falsy literal
- it returns all triples
- it removes all triples

This is the same kind of bug as in https://github.com/RDFLib/rdflib/issues/2621.

### PR DESCRIPTION
**Pull request by eilmiv**
Fixes https://github.com/devkral/rdflib-django3/issues/9

### CODE REVIEW

**Comment by eilmiv** [comment]
@devkral Please let me know if I should change or test something more.

**Comment by devkral** [comment]
== and !=  are dangerous comparisons with None.

There are also some unrelated changes

I will refactor it.

**Comment by devkral** [comment]
when I overtook this project, I was not that deep in python and django ;)

**Comment by eilmiv** [comment]
> == and != are dangerous comparisons with None.
> 
> There are also some unrelated changes
> 
> I will refactor it.

Thank you very much.

The reason I chose `!=` over `is not` was that this is used in [rdflib](https://github.com/RDFLib/rdflib/blob/c9eb7a9368444a6f3b3106575486ddae001706b9/rdflib/plugins/stores/memory.py#L142), and I was unsure if there is some intention behind this. But I agree, `is not` would be better.

**Comment by devkral** [comment]
Most probably both ways will work, with != == breaking on special input

**Pull request closed without merging**
